## Service definition ##
application:
  schemaVersion: 0.0.1
  name: TestAppWebProjects
  services:
    - name: WebSiteProject
      description: WebSiteProject description.
      osType: Windows
      codePackages:
        - name: WebSiteProject
          image: websiteproject:dev
          endpoints:
            - name: WebSiteProjectListener
              port: 20000
          environmentVariables:
            - name: ASPNETCORE_URLS
              value: http://+:20000
#            - name: ApplicationInsights:InstrumentationKey
#              value: "<Place AppInsights key here, or reference it via a secret>"
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: TestAppWebProjectsNetwork